# Generated by Django 4.2.7 on 2025-09-14 20:18

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Név')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='inventory.category', verbose_name='Szülő kategória')),
            ],
            options={
                'verbose_name': 'Kategória',
                'verbose_name_plural': 'Kategóriák',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Név')),
                ('description', models.TextField(blank=True, verbose_name='Leírás')),
                ('sku', models.CharField(help_text='Egyedi cikkszám', max_length=50, unique=True, verbose_name='Cikkszám')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ár')),
                ('stock_quantity', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Készlet mennyiség')),
                ('min_stock_level', models.IntegerField(default=0, help_text='Figyelmeztetés alatt ez a szint', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum készlet szint')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Módosítva')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.category', verbose_name='Kategória')),
            ],
            options={
                'verbose_name': 'Termék',
                'verbose_name_plural': 'Termékek',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Név')),
                ('contact_person', models.CharField(blank=True, max_length=100, verbose_name='Kapcsolattartó')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Telefon')),
                ('address', models.TextField(blank=True, verbose_name='Cím')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
            ],
            options={
                'verbose_name': 'Szállító',
                'verbose_name_plural': 'Szállítók',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('IN', 'Beérkezés'), ('OUT', 'Kivétel'), ('ADJUSTMENT', 'Korrekció')], max_length=10, verbose_name='Mozgás típusa')),
                ('quantity', models.IntegerField(verbose_name='Mennyiség')),
                ('reason', models.TextField(blank=True, verbose_name='Indok')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Létrehozva')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Létrehozó')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.product', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Készletmozgás',
                'verbose_name_plural': 'Készletmozgások',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='inventory.supplier', verbose_name='Szállító'),
        ),
    ]
