# Generated by Django 4.2.7 on 2025-09-15 12:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='ean13',
            field=models.CharField(blank=True, help_text='Egyedi EAN-13 vonalkód', max_length=13, null=True, unique=True, verbose_name='EAN-13 Vonalkód'),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Termékkép'),
        ),
        migrations.AddField(
            model_name='product',
            name='net_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Nettó ár'),
        ),
        migrations.AddField(
            model_name='product',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=27.0, max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='ÁFA kulcs (%)'),
        ),
    ]
