# Generated by Django 4.2.7 on 2025-09-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_remove_product_price_product_ean13_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/', verbose_name='Kép')),
                ('alt_text', models.CharField(blank=True, max_length=200, verbose_name='Alternatív szöveg')),
                ('is_main', models.BooleanField(default=False, verbose_name='Fő kép')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sorrend')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltve')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='inventory.product', verbose_name='Termék')),
            ],
            options={
                'verbose_name': 'Termékkép',
                'verbose_name_plural': 'Termékképek',
                'ordering': ['order', 'created_at'],
                'unique_together': {('product', 'is_main')},
            },
        ),
    ]
