# Generated by Django 4.2.7 on 2025-09-15 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productimage',
            unique_together=set(),
        ),
    ]
