name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        ports: ["5432:5432"]
        env:
          POSTGRES_DB: jerv_test
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd "pg_isready -U postgres -d jerv_test"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements/requirements.txt
      - name: Wait for Postgres
        run: |
          until pg_isready -h localhost -p 5432 -U postgres; do echo "Waiting..."; sleep 1; done
      - name: Run migrations and tests
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:5432/jerv_test
        run: |
          python manage.py migrate --noinput
          python manage.py test --verbosity=2
